from flask import Blueprint, render_template, abort, session, request, redirect, flash, url_for, send_from_directory, jsonify
from functools import wraps
from flask_login import current_user
import os
from core import db
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import uuid
from reportlab.lib.units import inch
from datetime import date
import base64
import numpy as np
import cv2
from io import BytesIO
from PIL import Image
import json


plugin_dir = os.path.dirname(os.path.abspath(__file__))
attendance_folder = os.path.join(plugin_dir, 'records')
if not os.path.exists(attendance_folder):
    os.mkdir(attendance_folder)

bp = Blueprint('aero', __name__, template_folder='templates', root_path=plugin_dir)


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.user_role != 'admin':
            abort(403) 
        return f(*args, **kwargs)
    return decorated_function

def teacher_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.user_role != 'teacher':
            abort(403)
        return f(*args, **kwargs)
    return decorated_function

@bp.route('/home/')
@teacher_only
def home():
    # for teachers
    from core.models import Attendance
    prev_rec = Attendance.query.filter_by(teacher=session['id']).order_by(Attendance.date_created.desc()).all()
    return render_template('aero-home.html', data=prev_rec, record_folder = attendance_folder)

@bp.route('/download/<report_id>/')
@teacher_only
def download_report(report_id):
    filename = f"{report_id}.pdf"
    return send_from_directory(attendance_folder, filename, as_attachment=True)

@bp.route('/add-attendance/')
@teacher_only
def addAttendance():
    from core.models import Class, Student
    class_data = Class.query.filter_by(id=session['classID']).first()
    selected_class_id = request.args.get('class_id')
    
    students = []
    if selected_class_id:
        students = Student.query.filter_by(classID=selected_class_id).all()
    cls_data= {
        'className': class_data.name,
        'classID': class_data.id
    }
    return render_template('aero-add-attendance.html', classes = cls_data, students=students )


@bp.route('/save-attendance', methods=['POST'])
@teacher_only
def saveAttendance():
    if request.method =='POST':
        class_id = request.form.get('class_id')
        today = date.today()
        attendance_id = f"ATD-{uuid.uuid4().hex[:8].upper()}" 
        from core.models import Class
        cls = Class.query.get(class_id)
        attendance_data = [["Roll No", "Name", "Status"]]
        for key, value in request.form.items():
            if key.startswith('status_'):
                student_id = key.replace('status_', '')
                from core.models import Student
                student = Student.query.get(student_id)
                
                attendance_data.append([student.id, f"{student.fname} {student.lname}", value.upper()])

        
        filename = f"{attendance_id}.pdf"
        full_path = os.path.join(attendance_folder, filename)

       
        course_title = cls.name
        course_code = class_id

        data = [["Sr#", "Student ID", "Name", "Status"]]
        absent_rows = []

        counter = 1
        for key, value in request.form.items():
            if key.startswith('status_'):
                student_id = key.replace('status_', '')
                student = Student.query.get(student_id)
                status_text = value.upper()
                
                data.append([counter, student.id.upper(), f"{student.fname} {student.lname}", status_text])
                
                if status_text == "ABSENT":
                    absent_rows.append(counter)
                counter += 1

        filename = f"{attendance_id}.pdf"
        full_path = os.path.join(attendance_folder, filename)

        doc = SimpleDocTemplate(full_path, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=18)
        styles = getSampleStyleSheet()
        elements = []

        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], alignment=1, fontSize=18, spaceAfter=2)
        sub_title_style = ParagraphStyle('SubTitle', parent=styles['Normal'], alignment=1, fontSize=10, bold=True)
        
        from core.models import Settings
        settings = Settings.query.get('001')

        elements.append(Paragraph(settings.orgName, title_style))
        elements.append(Paragraph("Automated report generated by JAZARI", sub_title_style))
        elements.append(Paragraph(f"Attendance Report - {today.strftime('%B %Y')}", sub_title_style))
        elements.append(Spacer(1, 0.2 * inch))

        details_data = [
            [f"Course Title: {course_title}", f"Course Code: {course_code.upper()}"],
            [f"Attendance ID: {attendance_id}", f"Date: {today}"]
        ]
        details_table = Table(details_data, colWidths=[4*inch, 2.5*inch])
        details_table.setStyle(TableStyle([
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ]))
        elements.append(details_table)
        elements.append(Spacer(1, 0.3 * inch))

        atd_table = Table(data, colWidths=[0.5*inch, 1.2*inch, 3.5*inch, 1.3*inch])
        
        table_style_commands = [
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (1,-1), 'CENTER'),
            ('ALIGN', (3,0), (3,-1), 'CENTER'), 
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LEFTPADDING', (2,0), (2,-1), 10), 
        ]

        for row_idx in absent_rows:
            table_style_commands.append(('TEXTCOLOR', (3, row_idx), (3, row_idx), colors.red))
            table_style_commands.append(('FONTNAME', (3, row_idx), (3, row_idx), 'Helvetica-Bold'))

        atd_table.setStyle(TableStyle(table_style_commands))
        elements.append(atd_table)

        try:
            doc.build(elements)

            from core.models import Attendance
            new_report = Attendance(
                id=attendance_id,
                teacher=session['id'],
                class_id=class_id,
                # date_created=today
            )
            db.session.add(new_report)
            db.session.commit()

            flash(f"Report {attendance_id} generated and saved!", "success")

        except Exception as e:
            db.session.rollback()
            print(f"PDF Error: {e}")
            flash("Failed to generate PDF report.", "danger")

        return redirect(url_for('aero.home'))


@bp.route('/settings')
@admin_only
def settings():
    # for the Admin only
    import cv2

    def list_ports():
        non_working_ports = []
        dev_port = 0
        working_ports = []
        
        while len(non_working_ports) < 6: 
            camera = cv2.VideoCapture(dev_port)
            if not camera.isOpened():
                non_working_ports.append(dev_port)
                print(f"Port {dev_port} is not working.")
            else:
                is_reading, img = camera.read()
                w = camera.get(3)
                h = camera.get(4)
                if is_reading:
                    print(f"Port {dev_port} is working and reads images ({w} x {h})")
                    working_ports.append(dev_port)
                else:
                    print(f"Port {dev_port} is present but does not read.")
            
            camera.release()
            dev_port += 1
        return working_ports

    available_cameras = list_ports()
    print(f"Available camera indexes: {available_cameras}")

    return render_template('aero-settings.html', cameras = available_cameras)


@bp.route('/settings', methods=['POST', 'GET'])
@admin_only
def update_settings():
    # for the Admin only
    if request.method=='POST':
        port = request.form.get('port')
        from core.models import Class
        from core import db
        try:
            db.session.query(Class).update({
                "room": port
            }, synchronize_session=False)
            
            db.session.commit()
            flash("Settings updated successfully.", 'success')
            return redirect(url_for('aero.settings'))
        except Exception as e:
            flash("Failed to update admin.", 'error')
            print(e)
            return redirect(url_for('aero.settings'))



@bp.route('/ai-recognize', methods=['POST'])
def ai_recognize():
    data = request.get_json()
    image_data = data.get('image') 
    class_id = data.get('class_id')
    from core.models import Student
    students = Student.query.filter_by(classID=class_id).all()

    embeddings = []

    for student in students:
        embeddings.append(json.loads(student.embedding))

    from utils.utilities import find_faces
    try:
        img = decode_base64_image(image_data)
        res = {}
        for st in students:
            res[st.id] = 'absent'
        faces = find_faces(img, embeddings)
        for face in faces:
            res[face] = 'present'
        return jsonify({
            "success": True,
            "attendance": res
        })
    except Exception as e:
        print(e)
    
    return None




def decode_base64_image(image_data):
    if "," in image_data:
        header, encoded = image_data.split(",", 1)
    else:
        encoded = image_data

    decoded_bytes = base64.b64decode(encoded)

    nparr = np.frombuffer(decoded_bytes, np.uint8)
    opencv_img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    return opencv_img



@bp.route('/delete/<report_id>/')
@teacher_only
def delete_report(report_id):
    from core.models import Attendance
    report = Attendance.query.filter_by(id=report_id).first()

    if not report:
        flash("Error: Report no longer exists.", "error")
        return redirect(url_for('aero.home'))

    try:
        filename = f"{report_id}.pdf"
        file_path = os.path.join(attendance_folder, filename)
        
        if os.path.exists(file_path):
            os.remove(file_path)
            print(f"File {filename} deleted from storage.")
        else:
            print(f"Note: File {filename} was already missing from storage.")

        db.session.delete(report)
        db.session.commit()

        flash(f"Report {report_id} has been permanently deleted.", "success")

    except Exception as e:
        db.session.rollback() 
        print(f"Delete Error: {e}")
        flash(f"An error occurred while deleting: {str(e)}", "error")

    return redirect(url_for('aero.home'))
