from flask import Blueprint, render_template, abort, session, request, redirect, flash, url_for, send_from_directory, jsonify
from functools import wraps
from flask_login import current_user
import os
from core import db
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.graphics.charts.barcharts import VerticalBarChart
import uuid
from reportlab.lib.units import inch
from datetime import date
from werkzeug.utils import secure_filename
import json
from flask_socketio import SocketIO, emit
import time
import threading
from core import socketio
from dotenv import load_dotenv

load_dotenv()


plugin_dir = os.path.dirname(os.path.abspath(__file__))
records_folder = os.path.join(plugin_dir, 'records')
if not os.path.exists(records_folder):
    os.mkdir(records_folder)

uploads_folder = os.path.join(plugin_dir, '.uploads')
if not os.path.exists(uploads_folder):
    os.mkdir(uploads_folder)

env_file = os.path.join(plugin_dir, '.env')


bp = Blueprint('zenith', __name__, template_folder='templates', root_path=plugin_dir, static_folder='static')


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.user_role != 'admin':
            abort(403) 
        return f(*args, **kwargs)
    return decorated_function

def teacher_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.user_role != 'teacher':
            abort(403)
        return f(*args, **kwargs)
    return decorated_function

@bp.route('/home/')
@teacher_only
def home():
    # for teachers
    from core.models import Quiz
    active_quizzes = Quiz.query.filter(
        Quiz.teacher == session['id'],
        Quiz.status.in_(['active', 'processing']) 
    ).order_by(Quiz.date_created.desc()).all()

    prev_rec = Quiz.query.filter(
        Quiz.teacher == session['id'],
        Quiz.status == 'ended'
    ).order_by(Quiz.date_created.desc()).all()
    return render_template('zenith-home.html', data=prev_rec, record_folder = records_folder, active_data=active_quizzes)

@bp.route('/download/<report_id>/')
@teacher_only
def download_report(report_id):
    filename = f"{report_id}.pdf"
    return send_from_directory(records_folder, filename, as_attachment=True)

def generate_quiz_report(quiz_id):
    print('generating report ..')
    table_name = f"temp_{quiz_id}"
    results = db.session.execute(text(f"SELECT * FROM {table_name}")).fetchall()
    if not results:
        return False, "No data found."

    print(results)

    scores = [r.obtained_marks for r in results]
    names = [r.student_name for r in results]
    avg_score = sum(scores) / len(results)
    max_score, min_score = max(scores), min(scores)
    
    top_scorer = ", ".join([r.student_name for r in results if r.obtained_marks == max_score])
    lowest_scorer = ", ".join([r.student_name for r in results if r.obtained_marks == min_score])

    today = date.today() # [cite: 5]
    filename = f"{quiz_id}.pdf"
    full_path = os.path.join(records_folder, filename)
    
    doc = SimpleDocTemplate(full_path, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=18)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], alignment=1, fontSize=18, spaceAfter=2)
    sub_title_style = ParagraphStyle('SubTitle', parent=styles['Normal'], alignment=1, fontSize=10, bold=True)
    
    from core.models import Settings
    settings = Settings.query.get('001')
    elements.append(Paragraph(settings.orgName, title_style)) 
    elements.append(Paragraph("Automated report generated by JAZARI", sub_title_style))
    elements.append(Paragraph(f"Quiz Assessment Report - {today.strftime('%B %Y')}", sub_title_style))
    elements.append(Spacer(1, 0.2 * inch))

    details_data = [
        [f"Quiz ID: {quiz_id}"],
        [f"Report ID: {quiz_id}.pdf", f"Date: {today}"]
    ]
    details_table = Table(details_data, colWidths=[4*inch, 2.5*inch])
    details_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
    ]))
    elements.append(details_table)
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Score Distribution Chart", styles['Heading3']))
    drawing = Drawing(400, 200)
    bc = VerticalBarChart()
    bc.x = 50
    bc.y = 50
    bc.height = 125
    bc.width = 300
    bc.data = [scores]
    bc.categoryAxis.categoryNames = names
    bc.valueAxis.valueMin = 0
    bc.valueAxis.valueMax = results[0].total_marks # Scale to total possible marks
    bc.valueAxis.valueStep = 1
    bc.barSpacing = 2
    drawing.add(bc)
    elements.append(drawing)
    elements.append(Spacer(1, 0.2 * inch))

    summary_data = [
        ["Metric", "Value"],
        ["Average Score", f"{avg_score:.2f}"],
        ["Top Scorer(s)", f"{top_scorer} ({max_score})"],
        ["Lowest Scorer(s)", f"{lowest_scorer} ({min_score})"]
    ]
    summary_table = Table(summary_data, colWidths=[2*inch, 4.5*inch])
    summary_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,1), (0, -1), colors.darkblue),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.3 * inch))

    data = [["Sr#", "Student ID", "Name", "Score"]]
    for i, r in enumerate(results, 1):
        data.append([i, r.student_id, r.student_name, r.obtained_marks])

    res_table = Table(data, colWidths=[0.5*inch, 1.5*inch, 3*inch, 1.5*inch])
    res_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ALIGN', (0,0), (1,-1), 'CENTER'),
        ('ALIGN', (3,0), (3,-1), 'CENTER'),
    ]))
    elements.append(res_table)

    doc.build(elements)
    return True, full_path

@bp.route('/settings')
@admin_only
def settings():
    
    return render_template('zenith-settings.html')


@bp.route('/settings', methods=['POST', 'GET'])
@admin_only
def update_settings():
    # for the Admin only
    if request.method=='POST':
        model = request.form.get('model')
        api = request.form.get('api')
        with open(env_file, 'w') as f:
            data = {
                'OPENROUTER_API_KEY': api,
                'MODEL': model
            }
            f.write(str(data))
        flash("Settings updated.", 'success')
        return render_template('zenith-settings.html')




def generate_quiz(app, id, data, name, teacher, classID, pdf_path, topics, count, difficulty, status):
    with app.app_context():
        from core.models import Quiz
        from sqlalchemy import text
        
        try:
            socketio.emit('quiz_progress', {'percentage': 10, 'message': 'Extracting data...', 'status': 'processing'})
            print('='*20)
            print(data)
            print(data['OPENROUTER_API_KEY'])
            from utils.utilities import quiz_generator
            generated_quiz = quiz_generator(api_key=data['OPENROUTER_API_KEY'], model=data['MODEL'], difficulty=difficulty, count=count, quiz_topics=topics, quiz_doc=pdf_path)
            
            socketio.emit('quiz_progress', {'percentage': 50, 'message': 'AI generating questions...', 'status': 'processing'})
            
            if not generated_quiz or generated_quiz.get('redflag'):
                raise Exception("AI flagged the content or failed to generate.")

            time.sleep(2) 
            socketio.emit('quiz_progress', {'percentage': 80, 'message': 'Saving to database...', 'status': 'processing'})
            
            quiz = Quiz.query.get(id)
            if not quiz:
                raise Exception("Quiz record lost during processing.")
                
            quiz.status = 'active'
            quiz.embedding = generated_quiz['quiz_JSON']
            db.session.commit()
            
            table_name = f"temp_{id}"
            query = text(f"""
            CREATE TABLE {table_name} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_id VARCHAR(50) NOT NULL,
            student_name VARCHAR(100),
            total_marks FLOAT,
            obtained_marks FLOAT,
            submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
            """)
            db.session.execute(query)
            db.session.commit()
            
            socketio.emit('quiz_progress', {'percentage': 100, 'message': 'Quiz Ready!', 'status': 'completed'})

        except Exception as e:
            db.session.rollback()
            print(f"Generation Error: {e}")
            from core.models import Quiz
            try:
                Quiz.query.filter_by(id=id).delete()
                db.session.commit()
                print(f"Successfully deleted stuck quiz {id} from database.")
            except Exception as cleanup_e:
                print(f"Failed to delete stuck quiz: {cleanup_e}")

            socketio.emit('quiz_progress', {'percentage': 0, 'message': f'Error: {str(e)}', 'status': 'error'})

        finally:
            # FIX 4: Close the thread's connection to the database to prevent hanging locks
            db.session.remove()


def generate_unique_id(prefix):
    import uuid
    return f"{prefix}_{str(uuid.uuid4()).split('-')[0].upper()}"


@bp.route('/start-generation', methods=['POST'])
def start_generation():
    name = request.form.get('name')
    pdf_file = request.files.get('pdf')
    topics = request.form.get('topics')
    count = request.form.get('count')
    difficulty = request.form.get('difficulty')
    teacher = session['id']
    from core.models import Teacher
    classID = Teacher.query.filter_by(id=teacher).first().classID
    status = 'processing'
    id = generate_unique_id('QZ')
    path = None
    print(id, name, teacher, classID, pdf_file, topics, count, difficulty, status)

    if pdf_file:
        filename = secure_filename(pdf_file.filename)
        path = os.path.join(uploads_folder, filename)
        pdf_file.save(path)
    try:
        from core.models import Quiz
        pending_quiz = Quiz(
            id=id,
            name=name,
            teacher=teacher,
            class_id=classID,
            status=status,
            embedding=None
        )
        db.session.add(pending_quiz)
        db.session.commit()
    except Exception as e:
        return jsonify(success=False, message="Database error")

    from flask import current_app 
    with open(env_file, 'r') as f:
        data = f.read()
        if data == '':
            try:
                from core.models import Quiz
                Quiz.query.filter_by(id=id).delete()
                db.session.commit()
            except Exception as cleanup_e:
                print(f"Failed to delete stuck quiz: {cleanup_e}")
                return jsonify({
                "success": False, 
                "message": "No API key found. Please update your settings.",
                "redirect": url_for('zenith.home') 
            }), 400
        else:
            try:
                data = eval(data)
            except Exception as e:
                Quiz.query.filter_by(id=id).delete()
                db.session.commit()
                
                print(f"Failed to delete stuck quiz: {cleanup_e}")
                return jsonify(success=False, message="Corrupted settings file."), 500
      
    app_instance = current_app._get_current_object()
    
    thread = threading.Thread(
        target=generate_quiz, 
        args=(app_instance, id, data, name, teacher, classID, path, topics, count, difficulty, status)
    )
    thread.daemon = True #
    thread.start()
   
    return jsonify(success=True, quiz_id=id)


@bp.route('/teacher-dashboard/<quiz_id>')
@teacher_only
def teacher_dashboard(quiz_id):
    quiz_id = f"{quiz_id}"
    from core.models import Quiz
    quiz_data = Quiz.query.filter_by(id=quiz_id).first()
    from sqlalchemy import text
    table_name = f'temp_{quiz_id}'
    query = text(f"SELECT id, student_id, student_name, obtained_marks FROM {table_name} ORDER BY submitted_at DESC")
    result = db.session.execute(query)
    student_results = result.fetchall()
    return render_template('zenith-teacher-dasboard.html',quiz_id = quiz_id, data = quiz_data, qr_code = url_for('zenith.attempt_quiz', quiz_id=quiz_id, _external=True), result = student_results)

from sqlalchemy import text

@bp.route('/end-quiz', methods=['POST'])
def end_quiz():

    data = request.get_json()

    quiz_id = data.get('quiz_id')

    from core.models import Quiz

    if not quiz_id:
        return jsonify({"status": "error", "message": "Missing Quiz ID"}), 400

    try:
        generate_quiz_report(quiz_id)
        Quiz.query.filter_by(id=quiz_id).update({"status": "ended"})
        db.session.commit()
        table_name = f"temp_{quiz_id}"
        drop_query = text(f"DROP TABLE IF EXISTS {table_name}")
        db.session.execute(drop_query)
        db.session.commit()

        return jsonify({
            "status": "success", 
            "message": f"Quiz {quiz_id} set to ended and {table_name} removed."
        }), 200

    except Exception as e:
        db.session.rollback()
        print(f"Error: {e}")
        return jsonify({"status": "error", "message": str(e)}), 500


@bp.route('/check-attempt', methods=['POST'])
def check_attempt():
    data = request.get_json()
    roll_id = data.get('std_id')
    quiz_id = data.get('quiz_id')
    
    try:
        table_name = f'temp_{quiz_id}'
        query = text(f"SELECT 1 FROM {table_name} WHERE student_id = :roll_id")
        result = db.session.execute(query, {"roll_id": roll_id}).fetchone()
        
        exists = result is not None
        return jsonify({"exists": exists}), 200
    except Exception as e:
        return jsonify({"exists": False}), 200


@bp.route('/attempt-quiz/<quiz_id>')
def attempt_quiz(quiz_id):
    quiz_id = f"{quiz_id}"
    from core.models import Quiz, Settings
    system_info = Settings.query.get('001')
    quiz_data = Quiz.query.filter_by(id=quiz_id).first()
    print(quiz_data)
    if quiz_data.status=='active':
        from utils.utilities import shuffler
        quiz_json = shuffler(quiz_data.embedding)
        return render_template('zenith-quiz.html', quiz_json = quiz_json, quiz_id = quiz_id, system_info = system_info)
    else:
        return render_template('zenith-error.html', quiz_id = quiz_id)

@bp.route('/submit-results', methods=['POST'])
def submit_results():
    data = request.get_json()
    name = data.get('student_name')
    roll_id = data.get('student_id')
    score = data.get('score')
    total = data.get('total')
    quiz_id = data.get('quiz_id')
    try:
        from sqlalchemy import text
        
        print(f"RECIEVED: {name} ({roll_id}) scored {score}/{total}. ")
        table_name = f'temp_{quiz_id}'
        print(table_name)
        query = text(f"""   
        INSERT INTO {table_name} (student_id, student_name, total_marks, obtained_marks) 
        VALUES (:roll_id, :name, :total, :score)
        """)        
        db.session.execute(query, {
            "roll_id": roll_id,
            "name": name,
            "total": total,
            "score": score
        })
        db.session.commit()
        return jsonify({"status": "success", "message": "Result recorded"}), 200
    except Exception as e:
        return jsonify({"status": "fail", "message": "Result not recorded"}), 400



@bp.route('/delete/<report_id>/')
@teacher_only
def delete_report(report_id):
    from core.models import Quiz
    report = Quiz.query.filter_by(id=report_id).first()

    if not report:
        flash("Error: Report no longer exists.", "error")
        return redirect(url_for('zenith.home'))

    try:
        filename = f"{report_id}.pdf"
        file_path = os.path.join(records_folder, filename)
        
        if os.path.exists(file_path):
            os.remove(file_path)
            print(f"File {filename} deleted from storage.")
        else:
            print(f"Note: File {filename} was already missing from storage.")

        db.session.delete(report)
        db.session.commit()

        flash(f"Report {report_id} has been permanently deleted.", "success")

    except Exception as e:
        db.session.rollback() 
        print(f"Delete Error: {e}")
        flash(f"An error occurred while deleting: {str(e)}", "error")

    return redirect(url_for('zenith.home'))
